<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InnerPsycheSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('inner_psyches')->insert([
            ['id' => 1 , 'signs' => 'll', 'meaning' => 'Ctižádostivost Vám rozhodně nechybí, díky čemuž jdete tvrdě za svým vytouženým cílem stoupajícím po strmé cestě kariéry.Máte jasno, kdo a jakým způsobem s vámi manipuluje. Vyhýbáte se situacím, které nejsou pro vás vhodné a vyhovující. V každé situaci umíte dobře a pohotově reagovat. Snadno si získáváte přátele, těžko však přijímáte odmítnutí. Nemáte rádi nepořádek, lenost a pochlebování. Jste odvážný a milujete dobrodružství. Někdy býváte vnitřně tvrdý. K ústupu vás přimějí pouze přesvědčivé argumenty. Máte pocit odpovědnosti k vaší rodině. Snažíte se jí materiálně zabezpečit.'],
            ['id' => 2 , 'signs' => 'rr', 'meaning' => 'Gratulujeme, jste vnitřně harmonický a klidný člověk. Oplýváte velkou dávkou empatie, proto vnímáte pocity a emoce vašeho okolí. Vnitřní harmonii ladíte ve společnosti vašich přátel nebo při aktivitách, které se časem stávají vašimi hobby – je soulad vynaložené energie a vykonané práce. Relaxace v přírodě a síla rodinného krbu je přímo odměnou pro vaši duši. Jste mírumilovný, skvěle navozujete pocit bezpečí, citového zázemí a jistoty. Vnitřně dobře znáte své kvality. Znáte tedy důvod k tomu, aby byly skryty pro vaše okolí a veřejnost?'],
            ['id' => 3 , 'signs' => 'lr', 'meaning' => 'Jste činorodý člověk, rád v pohybu a v akci. Životní překážky vnímáte jako výzvy, jste plný energie a soutěživosti. Jednáte rázně ve jménu svého ega a dokazujete si svoje kvality. Hlavní vaše charakteristika je individualista. Máte velkou potřebu pozornosti, chcete dosáhnout respektu vašeho okolí. Spontánně pomáháte ostatním, býváte však zklamán, když není vaše pomoc opětována. Pokud cítíte emoční zázemí, jste odhodlán dosáhnout jakéhokoliv cíle.Rozpor ve vaší mysli a emocemi ve vás vyvolává nepokoj, který se projevuje až výbuchy hněvu, náladovostí a pocitem nejistoty. Přetvořte energii vzteku a hněvu do akce, zkuste například aktivní odpočinek v přírodě a pohled na svět z perspektivy. Naučte se vnímat svou realitu z jiného rozměru – získejte nadhled nad sebou a ostatními.'],
            ['id' => 4 , 'signs' => 'rl', 'meaning' => 'Empatie je pro vás životně důležitá. Milujete harmonii, pohodu, něžné doteky a jemnost. Vaše silné sociální cítění se odráží v pomoci druhým.  Pokud jsou na vás kladené vysoké nároky, cítíte se v napětí, nervózní. Máte neklidné myšlenky a často ruší váš spánek. Často cítíte neklid, který vyvolává rozpor mezi vašimi myšlenkami a emocemi. Nahromaděný neklid se pak projevuje návaly vzteku a hněvu, doprovází je pocit nejistoty.  Mžikem se vám mění nálada. Cesta k rovnováze vede skrze aktivní pobyt v přírodě, nalezení citového zázemí. Výsledkem je snazší dosažení vašich tužeb a přání.'],
            ['id' => 5 , 'signs' => 'bb', 'meaning' => 'Máte silnou vůli a jste pracovitý.Práce pro vás znamená mnoho, berete ji vážně a zodpovědně. Jste rozvážný, o svých krocích přemýšlíte. Máte cit pro spravedlnost, jste nepodplatitelný. Vše, co činíte, konáte s neobvyklou dokonalostí a přesností. V opojení dokonalé práce, zapomínáte na sebe sama, rodinu a lásku. Máte zaběhnutý vlastní systém, jen těžko se přizpůsobujete novým směrům. Právě nastal čas zaměřit pozornost na čas určený jen vám, znovuobjevení vnitřní radosti a lásky.'],
            ['id' => 6 , 'signs' => 'bl', 'meaning' => 'Neradi poutáte na sebe pozornost, potřebujete však mít pocit vlastnění. Ve vztahu jste majetnický a máte tendence svého partnera omezovat. Od svého partnera požadujete věrnost a oddanost. Nevěru neodpouštíte. Ke vztahu přistupujete spíše racionálně, emoce v něm rozhodně nehrají prim.  Máte velký smysl pro povinnost, což způsobuje to, že ostatní pocity potlačujete. Vše dokonale plánujete a rozmýšlíte. V pracovních aktivitách jdete hned k jádru věci, přílišné řeči nesnášíte. Jste zaměřený na výsledek – zisk, pracovní postup, kariéra. Svou budoucnost máte naplánovanou léta dopředu. Máte rád pocit bezpečí a jistoty. Vyzkoušejte si váš dokonalý materiální svět doplnit o barevný svět emocí.'],
            ['id' => 7 , 'signs' => 'br', 'meaning' => 'Nalezení vnitřního kompromisu v situacích, které vám přináší život, je pro vás velmi důležité. Nečekané životní změny ve vás vyvolávají pocity nejistoty, berou vám doslova energii. Přestože žijete možná v přepychu a pohodlným životem, máte pocit, že vám něco podstatného schází. Materiálno je pro vás pomyslnou náplastí na bolavou duši. Citová stabilita a finanční jistota je pro vás známkou stability, bezpečí a klidu. Pomohla by vám blízká, empatická, vnímavá osoba, která potěší vaše srdce. Dotek a něžnosti jsou pro vás velmi důležité – činí vám potěšení. Vaše vnitřní napětí vám pomůže uvolnit pobyt v přírodě, aktivní odpočinek, samostudium a osobní rozvoj.'],
            ['id' => 8 , 'signs' => 'al', 'meaning' => 'Spoléhejte na svou vnitřní sílu, díky ní jste odolná osoba, připravená k obraně vůči všem protivníkům. Nesnášíte nudu, lidskou hloupost, omezování. Jste stále ve střehu, často si tímto postojem činíte z druhých nepřátele. Pokud vznikne spor, řešíte jej rychle a uhasíte případný oheň hned v zárodku. Pravdou je, že se necháte rychle vyprovokovat. Rád holdujete komplimentům, obdivu a potlesku. Vaše emoce by se daly přirovnat ke kováři, který kuje železo, dokud je ještě žhavé.'],
            ['id' => 9 , 'signs' => 'ar', 'meaning' => 'Od přírody jste přirozený optimista, upřímný a otevřený člověk. Vaše energie nemá mezí. Milujetesvobodu a nezávislost, ale přesto nedokážete žít osamoceně. Máte rádi vše, co k životu patří  - peníze, lásku, rodinu... Naplňuje vás pomoc druhým, někdy se vaše okolí, právem, diví nad vašimi smělými činy.Zamyslete se nad tím, že i vlastní osobě je třeba se chovat tolerantně a s náležitou úctou. Faktem je, že máte rádi věci pod kontrolou, jasné a výstižné.'],
            ['id' => 10 , 'signs' => 'ab', 'meaning' => 'Důležitý je pro vás pocit volnosti, svobody a neomezených možností, ať již fyzických tak psychických. Jste zdrojem velké energie, kterou je třeba uvolnit v pohybu a v aktivním odpočinku. Jste odvážný a srdcem dobrodruh. Milujete harmonické prostředí, proto ve stísněných prostorách přímo trpíte. Máte někdy až příliš velký pocit zodpovědnosti. Kladete si otázky jak zabezpečit rodinu. Milujete dotyky a něžnosti. Naplňuje vás pocit z dobře vykonané práce, kde vidíte jasné výsledky.'],
            ['id' => 11 , 'signs' => 'lb', 'meaning' => 'Jste silný hráč, velký individualista. Toužíte po emoční, finanční a materiální stabilitě. Máte rád hezké věci, hojnost a přepych. Když milujete, tak naplno, rád dáváte dárky, avšak očekáváte, že to samé budou dělat i ti ostatní. Někdy toto bývá zdrojem vašeho zklamání. Rádi hodnotíte druhé, na druhé straně zpětnou vazbu a kritiku nepřijímáte.'],
            ['id' => 12 , 'signs' => 'rb', 'meaning' => 'Hledáte vnitřně kompromis a rovnováhu, hlavně v nečekaných životních situacích. Právě životní a emoční výkyvy vám působí zmatek a pocit nejistoty a stagnace. Stále vás provází myšlenka, že vám něco podstatného v životě chybí, třebaže žijete v blahobytu a pohodě. Vnímáte, že materiální věci jsou pro vás pouhou náplastí na bolavou duši. Hledejte spřízněnou empatickou duši, která vám bude rozumět. V pocitu rovnováhy vás ujistí vřelé doteky, aktivní odpočinek, příroda a poznání vlastní duše. Máte kultivované vystupování, rádi zanecháváte dobrý dojem. Jste praktický a pracovitý.'],
            ['id' => 13 , 'signs' => 'ba', 'meaning' => 'Překážky? Dobře víte, že neexistují, jsou pro vás výzvou, jak jít na své cestě dál. Přijímáte nové výzvy a podněty, jak je život přináší, využíváte každé možnosti, jak je zužitkovat pro vlastní rozvoj a život. Jste zodpovědný, v určitých momentech je pro vás těžké přijmout kritiku. Děláte-li jakoukoliv práci, činnost, konáte tak s nasazením, jste si vědom výhod i nevýhod a přijímáte veškerou odpovědnost. Jste sebevědomý, máte rád slova uznání. Na okolí můžete působit dominantním dojmem. Jste naladěný na úspěch, prosperitu a seberealizaci. K dokonalosti vám postačí odbourat malé emoční bloky.'],
            ['id' => 14 , 'signs' => 'aa', 'meaning' => 'Přirozený vůdce, plný energie a elánu. Zamyslete se nad tím, jakým způsobem zacházíte s vaší vnitřní silou, zda vaše sebeovládání je vyrovnané, zda příliš brzy neztrácíte rovnováhu... Věnujte pozornost tomu, zda někdy nezacházíte do přílišných krajností, čím překročíte určitou mez.Vše ve svém okolí analyzujete. Máte společenského ducha a zajímavé intelektuální myšlení. Máte respekt k autoritám, někdy se však zamotáváte do přílišných argumentu a sporů. Pro nalezení harmonie potřebujete okruh dobrých přátel, humor, pohodu a štěstí. Co vám schází právě teď?'],
            ['id' => 15 , 'signs' => 'la', 'meaning' => 'Smysl pro povinnost, pořádek a sebedisciplina – hlavní charakteristiky pro vaši osobnost...Vnitřní pohodu cítíte, pokud máte pocit uznání, volnosti a svobody rozhodování. Jste ctižádostivý a máte na sebe vysoké požadavky s cílem prosadit se. Jste statečný a odvážný. Vaše dobré organizační schopnosti uplatníte ve vedoucích a odpovědných pozicích. Svou výbušnost a hádavost se snažte uvolnit v dynamických, adrenalinových sportech a aktivitách. Vynakládáte často hodně energie, abyste získali obdiv a sympatie. Risk = zisk ve vašem případě neplatí. Občas riskujete, jen abyste dokázali svou odvahu, sílu a smělost, nebo abyste dosáhli vytyčené cíle za každou cenu.'],
            ['id' => 16 , 'signs' => 'ra', 'meaning' => 'Rodinné zázemí a přátelé hrají u vás prim. Tyto dva světy považujete na bezpečné útočiště před nevlídným venkovním světem.  Ve svém životě máte velkou potřebu něžností, porozumění, rád se vracíte do minulosti. Jste idealista a někdy až sentimentální. Milujete harmonii, klid a pohodu. Máte silné sociální cítění, pomáháte nejen lidem, ale také zvířátkům. Pokud jsou na vás kladeny přílišné nároky, cítíte stres a tlak.Dostáváte se mimo svou komfortní zónu, což může způsobovat nespavost a neklid. Na jednu stranu jste plný fantazie a ideálů, avšak na straně druhé jste netrpělivý a lenivý. Často promarníte nedočkavostí „tu“ pravou příležitost, která by vám umožnila naplnit své sny a ideály. Vyhýbejte se alkoholu a drogám, jdou vám rychleji pod kůži. Peníze vám poskytují pocit svobody, umožňují vám cestovat, poznávat a žít v blahobytu.'],
        ]);
    }
}
