<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OuterPsycheSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('outer_psyches')->insert([
            ['id' => 1 , 'signs' => 'll', 'meaning' => 'Pokud se řekne slovo ctižádost, jste jejím přímým důkazem, rozhodně vám nechybí. Díky této hnací síle, jdete jasně a tvrdě za vytouženým cílem. Vaše kariérní cesta až strmě stoupá. V každé situaci umíte dobře a pohotově reagovat. Máte ostrý jazyk, který mnohdy způsobuje nedorozumění a komunikační šumy. Váš verbální projev potřebuje více diplomacie. Na jednu stranu jste odvážný, otevřený a milujete dobrodružství. Obrácená strana mince je, že působíte velmi autoritativně, avšak máte velké štěstí k získání pomoci jiných autorit. Vaše vystupování je sebejisté a přímé. Svým vnějším projevem působíte na své okolí odměřeně a přesvědčivě u některých vyvoláváte respekt u těch slabších strach. Prozkoumejte vaše možnosti, jak získat do vašeho vystupování více diplomacie a pocity strachu u jiných změnit na respekt.'],
            ['id' => 2 , 'signs' => 'rr', 'meaning' => 'Pokud vás někdo tlačí nebo přímo manipulujete, cítíte velký stres. Velmi citlivě vnímáte pocity a emoce. Navenek působíte citlivě, avšak velmi často se přizpůsobujete svému okolí nebo situaci. Jste člověk, který hledá alternativy a řeší situace mírovou cestou. Lidé, Vás vnímají jako emočního a charismatického člověka, který se v dané situaci dokáže přizpůsobit a hledat možnosti vyhovující většině. Zaměřte se na své pocity a emoce tak, abys zvýšili své sebevědomí, asertivitu a zbavili se zbytečného stresu. Vnímejte nové možnosti, jak projevit svou přirozenou autoritu a osobnost.'],
            ['id' => 3 , 'signs' => 'rl', 'meaning' => 'Někdy se vám stává, že popíráte sami sebe. Dlouho ustupujete a přizpůsobujete se požadavkům vašeho okolí. Pokud vám okolí začne křivdit, nebo brnkat na vaši citlivou strunurázem se měníte v útočného a verbálně agresivního bojovníka. Ovládání těchto bouřlivých emocí je pro vás až obtížné. Obracíte svou nevýhodu ve výhodu – snažíte se dlouhodobé podřizování využít ve vlastní prospěch. Naučte se jak efektivně a správně zvládat své emoce, získáte tím jasný a srozumitelný návod na úspěch.'],
            ['id' => 4 , 'signs' => 'lr', 'meaning' => 'Dominance a ráznost jsou vašimi hlavními rysy. Ba jste přímo o ní přesvědčeni. Máte potřebu vysvětlovat a obhajovat své názory, pokud však někdo argumentuje lépe než Vy, stáhnete se a svůj názor přizpůsobujete, přestože víte, že máte svou pravdu. V podstatě jste mírumilovný člověk, dlouho snášíte princip příkoří, pokud však přeteče kalich vaší trpělivosti, dokážete jít razantně za svým cílem. Pokud dokážete vyladit své rozpory, získáte stabilitu a jistotu.'],
            ['id' => 5 , 'signs' => 'bb', 'meaning' => 'Jste velmi pracovitý, usilovný a spolehlivý. Upřednostňujete povolání, kde je důležitá přesnost zodpovědnost. Pokud děláte profesi, která je středem vašeho zájmu, zde excelujete a stává se z vás odborník na slovo vzatý.  Na svoje okolí působíte melancholicky až chladně. Bezpečí a jistotu pociťujete spíše v rodinném prostředí. Vše i sebe máte vždy pod kontrolou. Rád budujete hmotné statky a „šetříte“ peníze. Můžete být považován za nerozhodného a sobeckého člověka. Pro zlepšení stačí jen trochu popustit opratě a konat akce s pravidlem 80:20.'],
            ['id' => 6 , 'signs' => 'bl', 'meaning' => 'Jste silný individualista, máte rád život v přepychu a hojnosti. Jste velmi houževnatý a pracovitý. Rád obdarováváte své přátele, ale očekáváte od nich, že budou dělat totéž směrem k vaší osobě. Zpětnou vazbu a kritiku berete příliš osobně a těžko ji snášíte. Avšak váš mrštný jazyk naopak zpětnou vazbu a kritiku rád uděluje. Obklopujete se krásnými a kvalitními věcmi, máte dobrý vkus. Svým způsobem jste velký estét.  Rád dáváte na obdiv své materiální statky. Nalezněte cestu, jakým způsobem lépe přijímat zpětnou vazbu, získáte tím výhodu stratéga a skvělého vůdce.'],
            ['id' => 7 , 'signs' => 'br', 'meaning' => 'Na svoje okolí působíte zdrženlivě, nenápadně a ostýchavě. Jste nerad středem pozornosti, spíše se držíte v ústraní.Nalezení stability v situacích, které vám přináší život je pro vás velmi důležité. Nečekané životní změny ve vás vyvolávají pocity nejistoty, berou vám doslova energii. Přestože žijete možná v přepychu a pohodlným životem,máte pocit, že vám něco podstatného schází. Materiálno je pro vás pomyslnou náplastí na bolavou duši. Citová stabilita a finanční jistota je pro vás známkou stability, bezpečí a klidu. Pomohla by vám blízká, empatická, vnímavá osoba, která potěší vaše srdce. Dotek a něžnosti jsou pro vás velmi důležité – činí vám potěšení. Vaše vnitřní napětí vám pomůže uvolnit pobyt v přírodě, aktivní odpočinek, samostudium a osobní rozvoj.'],
            ['id' => 8 , 'signs' => 'al', 'meaning' => 'Volnost a svoboda vám voní, přináší vám pocity harmonie. Oplýváte odvahou, statečností a zdravou ctižádostí. Ke spokojenému životu potřebujete prostor na seberealizaci, pochopení a uznání. Vaše dobré organizační schopnosti jsou Vám nápomocné ve vedoucích a odpovědných pozicích. Upřednostňujete vaše cíle nad záměry ostatních. Jste pln energie, výbušnýa někdy hádavý. Svůj přetlak vypouštíte v adrenalinových sportech, preferujete aktivní odpočinek. Rádi na sebe upozorňujete, toužíte po obdivu a sympatiích druhých.  Nasměřujte vaši plnou energii do záměrů, které vám přinášejí radost a užitek. Rázem pocítíte vámi oblíbený pocit volnosti a svobody.'],
            ['id' => 9 , 'signs' => 'ar', 'meaning' => 'Jste přirozený optimista. Otevřený a upřímný. Jste plný „nekonečné“ energie. Vaše racionální stránka je vyvážená s emoční. Šťastnými vás činní pomáhat druhým až svými šlechetnými činy uvádíte v úžas vaše okolí. Máte rádi peníze a chováte s nimi přátelský vtah. Volnost a potřeba nezištně pomáhat Vás dělá šťastným a naplněným. Vaše šlechetné smělé činy uvádějí v úžas okolní svět.  Přestože, jste velmi oddaný své rodině,o všechnyčleny se výborně staráte, skutečné představyvašeho rodinného života jsou jiné, často nenaplněné. Máte pocit, že si s partneremšpatně rozumíte, vázne vám komunikace, dochází k hádkám. Často se přesvědčujete o své pravdě. Dovolte si trochu povolit opratě a dopřát svému okolí více samostatnosti. Získáte tím prostor pro vlastní osobní růst, stanete se přirozenou autoritou.'],
            ['id' => 10 , 'signs' => 'ab', 'meaning' => 'Organizačně schopný!  Dobré organizační schopnosti vám pomáhají získat značné materiální statky. Velmi dobře se cítíte ve vedoucích a odpovědných funkcích. Stává se vám, že míváte konflikty s autoritami. Pokud je vaše velení a možnost řídit oslabena, ztrácíte během chvíle zájem o práci nebo činnost, kterou vykonáváte. Motivace slábne a vaše aktivita se pomalu vytrácí. Máte rádi uznání a prestiž. Velmi ochotně a rádi podstoupíte cestu, byť namáhavou k dosažení úspěchu a slávy. Jste rádi finančně zabezpečeni, v případě materiálních nejistot se cítíte ohroženi a nejste ve své vlastní kůži. Materiální ztráty nesete velmi těžce. Stačí jen malá změna ve vašich postojích a dosáhnete svých představ.'],
            ['id' => 11 , 'signs' => 'lb', 'meaning' => 'Ego a hojnost jsou vaším motorem. Jste silný individualista, máte rád život v přepychu a hojnosti. Rád obdarováváte své přátele, ale očekáváte od nich, že budou dělat totéž směrem k vaší osobě. Zpětnou vazbu a kritiku berete příliš osobně a těžko ji snášíte. Avšak váš mrštný jazyk naopak zpětnou vazbu a kritiku rád uděluje. Obklopujete se krásnými a kvalitními věcmi, máte dobrý vkus. Rád dáváte na odiv své materiální statky. Nalezněte cestu, jakým způsobem lépe přijímat zpětnou vazbu, získáte tím výhodu stratéga a skvělého vůdce.'],
            ['id' => 12 , 'signs' => 'rb', 'meaning' => 'Na své okolí působíte nenápadně a zdrženlivě. Příliš na sebe nepoutáte pozornost. Uvnitř jste jemný, dokážete být taktní s příjemným vystupováním. Na Nalezení stability v situacích, které vám přináší život je pro vás velmi důležité. Nečekané životní změny ve vás vyvolávají pocity nejistoty, berou vám doslova energii. Přestože žijete možná v přepychu a pohodlným životem,máte pocit, že vám něco podstatného schází. Materiálno je pro vás pomyslnou náplastí na bolavou duši. Citové zázemí a finanční jistota je pro vás známkou stability, bezpečí a klidu. Pomohla by vám blízká, empatická, vnímavá osoba, která potěší vaše srdce. Dotek a něžnosti jsou pro vás velmi důležité – činí vám potěšení. Vaše vnitřní napětí vám pomůže uvolnit pobyt v přírodě, aktivní odpočinek, samostudium a osobní rozvoj.'],
        ]);
    }
}
